# ===============================
# DATABASE
# ===============================

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/employee_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:12345678}

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================

server.port=${PORT:8082}